### ISSUE TITLE
Unable to run front end

### ISSUE THREAD

**Issue by SmritiChawla** [scPolyphony/polyphony-vis#9]
Thank you for this insightful work and this package, I have been trying to run the frontend using following commands:
git clone https://github.com/scPolyphony/polyphony-vis.git
cd /polyphony-vis
npm install
npm run start

Here is the screenshot of the terminal:
![image](https://user-images.githubusercontent.com/23184365/232505158-5cea0a42-a6da-40f6-8b3a-a6541678d96b.png)

It says compiled with warnings, App starts but it keeps on loading. Here is the screenshot of the app:
![image](https://user-images.githubusercontent.com/23184365/232505532-4c0e6dff-cfe2-4179-968a-8a7759fde9ae.png)

I will really appreciate, if you can help with me installation. Also, doest it require back end to be installed as well?

Thank you again for this great tool!!

**Comment by keller-mark** [comment]
Hi @SmritiChawla ,
This screenshot shows the front end running successfully. The backend does need to be running for the loading indicators to go away. Instructions for running the backend are here https://github.com/scPolyphony/polyphony-vis#run-polyphony-backend

I have closed this issue but feel free to continue the discussion about running the backend here or in a new issue at https://github.com/scPolyphony/polyphony

**Comment by SmritiChawla** [comment]
Thank you so much for your quick reply.
